### PR TITLE
Add cross wiki search prefix

### PR DESCRIPTION
**Pull request by LunarTwilight**
Figured this might be useful for seeing if stuff is being used across fandom, not really tried to the search prefix name if you want to change that, or I can change it to a command instead if y'all think that would be better.

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
Is this with a specific use case in mind? If you're trying to search for code, why isn't there a URL parameter limiting the search to MediaWiki namespace?

**Comment by LunarTwilight** [comment]
> Is this with a specific use case in mind? 

For seeing if config options or scripts or stylesheets are being imported, for example.

> If you're trying to search for code, why isn't there a URL parameter limiting the search to MediaWiki namespace?

Because user code pages exist?

**Comment by KockaAdmiralac** [comment]
Then why is it not limited to User and MediaWiki namespaces? Also, do you think there is there any benefit in having separate search prefixes for MediaWiki and User namespace searches?

**Comment by LunarTwilight** [comment]
> Then why is it not limited to User and MediaWiki namespaces?

I was thinking about suggesting that after I wrote my reply to you but then I kinda decided against it because I thought it might be useful for modules too as well as catching other pages that might have the search query on them as well, but I can limit it to a few namespaces if you want.

> Also, do you think there is there any benefit in having separate search prefixes for MediaWiki and User namespace searches?

maybe? I guess it wouldn't hurt but I don't really see a usercase to need to search just MW uses vs just user uses?

**Comment by Dorumin** [comment]
dumb

**Pull request closed without merging**
